# Generated by Django 5.2.7 on 2025-10-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
    ]
